/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador.java;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileReader;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
/**
 *
 * @author jago
 */
public class Ventana extends javax.swing.JFrame {

    private String file = (new File("src/compilador/fuente.txt").getAbsolutePath());
    int i = 1;
    
    private void openFile(){
        try {
            FileReader rf = new FileReader(file);
            BufferedReader rb = new BufferedReader(rf);
            String line;
            textSource.setText("");
            
            
            while ((line=rb.readLine())!=null) {   
                textLine.append(i+"\n");   
                textSource.append(line + "\n");
                i++;
            }
            rb.close();
        } catch (Exception e) {
            textMessenger.setForeground(Color.red);
            textMessenger.setText(e.getMessage());
        }
        
    }
    private void saveFile(){
        try {
            FileWriter wf = new FileWriter(file);
            BufferedWriter bf = new BufferedWriter(wf);
            bf.write(textSource.getText());
            textMessenger.setForeground(Color.blue);
            textMessenger.setText("file saved ...");
            bf.close();
        } catch (Exception e) {
            textMessenger.setForeground(Color.red);
            textMessenger.setText(e.getMessage());
        }
        
    }
    private void compiler(){
        saveFile();
        /** try {
                       
            Lexer lex = new Lexer(new FileReader(file));
            lex.yylex();
            if (lex.errlex.isEmpty()){
                textMessenger.setForeground(Color.blue);
                textMessenger.setText("Compilación correcta!!");
                textMessenger.append(lex.ts.toString());
            }
            else{
                textMessenger.setForeground(Color.red);
                textMessenger.setText(lex.errlex);
            }
        } catch (IOException e) {
                textMessenger.setForeground(Color.red);
                textMessenger.setText(e.getMessage());
        }**/
    }
    
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        openFile();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_play = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textSource = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textMessenger = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textLine = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuNew = new javax.swing.JMenuItem();
        mnuOpen = new javax.swing.JMenuItem();
        mnuSaveAs = new javax.swing.JMenuItem();
        mnuSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSave1 = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mnuApp = new javax.swing.JMenu();
        mnuCompiler = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compilador Fase 1 - Analisis Lexico");

        jToolBar1.setRollover(true);

        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/new-file.png"))); // NOI18N
        btn_new.setToolTipText("New");
        btn_new.setFocusable(false);
        btn_new.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_new.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_new);

        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btn_save.setToolTipText("Save");
        btn_save.setFocusable(false);
        btn_save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_save.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_save);

        btn_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/play-button.png"))); // NOI18N
        btn_play.setToolTipText("Compiler");
        btn_play.setFocusable(false);
        btn_play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_play.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_play);

        textSource.setColumns(20);
        textSource.setRows(5);
        textSource.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textSourceFocusGained(evt);
            }
        });
        textSource.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textSourceKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textSourceKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textSource);

        textMessenger.setEditable(false);
        textMessenger.setColumns(20);
        textMessenger.setRows(5);
        jScrollPane2.setViewportView(textMessenger);

        textLine.setEditable(false);
        textLine.setBackground(new java.awt.Color(204, 204, 204));
        textLine.setColumns(1);
        textLine.setLineWrap(true);
        textLine.setRows(1);
        textLine.setWrapStyleWord(true);
        textLine.setBorder(null);
        textLine.setRequestFocusEnabled(false);
        textLine.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textLineFocusGained(evt);
            }
        });
        jScrollPane3.setViewportView(textLine);

        mnuFile.setText("File");

        mnuNew.setText("New");
        mnuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewActionPerformed(evt);
            }
        });
        mnuFile.add(mnuNew);

        mnuOpen.setText("Open");
        mnuFile.add(mnuOpen);

        mnuSaveAs.setText("Save As ..");
        mnuFile.add(mnuSaveAs);

        mnuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSave.setText("Save");
        mnuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaveActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSave);
        mnuFile.add(jSeparator1);

        mnuSave1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuSave1.setText("Exit");
        mnuSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSave1ActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSave1);

        jMenuBar1.add(mnuFile);

        mnuEdit.setText("Edit");
        jMenuBar1.add(mnuEdit);

        mnuApp.setText("Application");

        mnuCompiler.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mnuCompiler.setText("Compiler");
        mnuCompiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCompilerActionPerformed(evt);
            }
        });
        mnuApp.add(mnuCompiler);

        mnuAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mnuAbout.setText("About as...");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuApp.add(mnuAbout);

        jMenuBar1.add(mnuApp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuNewActionPerformed

    private void mnuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaveActionPerformed
        saveFile();
    }//GEN-LAST:event_mnuSaveActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        saveFile();
    }//GEN-LAST:event_btn_saveActionPerformed

    private void mnuSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSave1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSave1ActionPerformed

    private void mnuCompilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCompilerActionPerformed
        compiler();
    }//GEN-LAST:event_mnuCompilerActionPerformed

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        compiler();
    }//GEN-LAST:event_btn_playActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
       JOptionPane.showMessageDialog(this, "Compiler");
    }//GEN-LAST:event_mnuAboutActionPerformed

    private void textSourceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSourceKeyTyped
        
    }//GEN-LAST:event_textSourceKeyTyped

    private void textSourceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textSourceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            textLine.append(i+"\n");
            i++;
        }
    }//GEN-LAST:event_textSourceKeyPressed

    private void textLineFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textLineFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textLineFocusGained

    private void textSourceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSourceFocusGained
        textLine.append(i+"\n");
        i++;
    }//GEN-LAST:event_textSourceFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_play;
    private javax.swing.JButton btn_save;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenu mnuApp;
    private javax.swing.JMenuItem mnuCompiler;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuNew;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JMenuItem mnuSave;
    private javax.swing.JMenuItem mnuSave1;
    private javax.swing.JMenuItem mnuSaveAs;
    private javax.swing.JTextArea textLine;
    private javax.swing.JTextArea textMessenger;
    private javax.swing.JTextArea textSource;
    // End of variables declaration//GEN-END:variables
}
